ipc = true
splash = false

wallpaper {
  monitor = DP-2
  path = /home/user/Pictures/wallpapers/wp10084942-4k-japan-anime-wallpapers.jpg
  fit_mode = cover
}

wallpaper {
  monitor = DP-3
  path = /home/user/Pictures/wallpapers/wp10084942-4k-japan-anime-wallpapers.jpg
  fit_mode = cover
}

# optional fallback, falls mal ein Monitorname anders ist:
wallpaper {
  monitor =
  path = /home/user/Pictures/wallpapers/wp10084942-4k-japan-anime-wallpapers.jpg
  fit_mode = cover
}
