ipc = true
splash = false

wallpaper {
  monitor = DP-2
  path = /home/user/Pictures/wallpapers/current-wallpaper/wallpaper.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-3
  path = /home/user/Pictures/wallpapers/current-wallpaper/wallpaper.png
  fit_mode = cover
}

# optional fallback, falls mal ein Monitorname anders ist:
wallpaper {
  monitor =
  path = /home/user/Pictures/wallpapers/current-wallpaper/wallpaper.png
  fit_mode = cover
}
